variables:
  IMAGE_REPO: "nexus.faridzarazvand.ir/kelaasor"
  IMAGE_NAME: "nodetest"
  IMAGE_TAG: "0.1"

stages:
  - build

build-job:
  tags:
    - kelaasor
  # image: dind:27
  stage: build
  script:
    - docker build -t $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG .