variables:
  IMAGE_REPO: "nexus.faridzarazvand.ir/kelaasor"
  IMAGE_NAME: "nodetest"
  IMAGE_TAG: "0.1"

stages:
  - build

build-job:
  tags:
    - kelaasor
  # image: node:18-alpine
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS $IMAGE_REPO
  script:
    - docker push $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG
