variables:
  IMAGE_REPO: "nexus.faridzarazvand.ir/kelaasor"
  IMAGE_NAME: "nodetest"
  IMAGE_TAG: "0.1"

stages:
  - build

build-job:
  tags:
    - kelaasor
  # image: dind:27
  stage: build
  script:
    - docker build -t $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG .

push-job:       # This job runs in the build stage, which runs first.
  tags:
    - kelaasor
  # image: node:18-alpine
  needs:
    - build-job
  stage: build
  before_script:
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS $IMAGE_REPO
    - echo $CI_REGISTRY_PASS | docker login -u $CI_REGISTRY_USER --password-stdin $IMAGE_REPO
  script:
    - docker push $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG
  after_script:
    - docker logout